<?php

namespace Tests\Unit;

use App\Item;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ItemControllerTest extends TestCase
{
    use RefreshDatabase;

    private $item;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $item = Item::create([
            'id' => 1,
            'nome' => 'Correr'
        ]);
        $this->item = $item;
    }

    public function testStore()
    {

        $found_item = Item::find(1);
        $this->assertEquals($found_item->nome, 'Correr');
    }

    public function testDestroy()
    {
        $item = Item::find(1);

        $this->assertDatabaseHas('items', ['id'=>$item->id]);
        Item::destroy($item->id);
        $this->assertDatabaseMissing('items', ['id'=>$item->id]);
    }

    public function testUpdateItemToDone(){
        $item = Item::find(1);
        $item->done = true;

        $this->assertEquals(true, $item->done);
    }

    public function testUpdateItemToUnDone()
    {
        $item = Item::find(1);
        $item->done = true;

        $this->assertEquals(true, $item->done);
        $item->done = false;
        $this->assertEquals(false, $item->done);
    }
}
